### PR TITLE
got groupmembers resource and user group relationship working

### LINKED ISSUE #38: GroupMembersResource

### PR DESCRIPTION
**Pull request by mgnielsen1**

### CODE REVIEW

**Comment by mgnielsen1** [comment]
and automatically adds owned_by_user to groups.users

**Comment by mgnielsen1** [comment]
also fixes the get user by group id endpoint

**Comment by mgnielsen1** [comment]
basically copied from here: https://www.tutorialspoint.com/sqlalchemy/sqlalchemy_orm_many_to_many_relationships.htm

**Review by wrmacdonald — APPROVED** [review]
looks good!

**Pull request merged**
